"""empty message

Revision ID: 0bd327c377bc
Revises: 981fefdb3d05
Create Date: 2017-03-19 16:27:48.400941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0bd327c377bc'
down_revision = '981fefdb3d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likelihood', sa.Column('value', sa.Integer(), nullable=True))
    op.alter_column('region', 'abbr',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('region', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('region', 'createdBy',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('region', 'tenant_uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('region', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('region', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('severity', sa.Column('value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('severity', 'value')
    op.alter_column('region', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('region', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('region', 'tenant_uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('region', 'createdBy',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('region', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('region', 'abbr',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('likelihood', 'value')
    # ### end Alembic commands ###
