"""empty message

Revision ID: 1cb5bbad9ece
Revises: 4c4f7f50775a
Create Date: 2017-03-17 15:43:11.191027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb5bbad9ece'
down_revision = '4c4f7f50775a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'region_abbr_title_tenant_uuid_key', 'region', type_='unique')
    op.create_unique_constraint(None, 'region', ['title', 'tenant_uuid'])
    op.create_unique_constraint(None, 'region', ['abbr', 'tenant_uuid'])
    op.drop_constraint(u'subRegion_abbr_title_tenant_uuid_key', 'subRegion', type_='unique')
    op.create_unique_constraint(None, 'subRegion', ['title', 'tenant_uuid'])
    op.create_unique_constraint(None, 'subRegion', ['abbr', 'tenant_uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subRegion', type_='unique')
    op.drop_constraint(None, 'subRegion', type_='unique')
    op.create_unique_constraint(u'subRegion_abbr_title_tenant_uuid_key', 'subRegion', ['abbr', 'title', 'tenant_uuid'])
    op.drop_constraint(None, 'region', type_='unique')
    op.drop_constraint(None, 'region', type_='unique')
    op.create_unique_constraint(u'region_abbr_title_tenant_uuid_key', 'region', ['abbr', 'title', 'tenant_uuid'])
    # ### end Alembic commands ###
