"""empty message

Revision ID: 2ef7a934b47f
Revises: 538a7b520587
Create Date: 2017-03-23 15:58:15.621112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef7a934b47f'
down_revision = '538a7b520587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('subRegion_uuid', sa.String(), nullable=True))
    op.drop_constraint(u'country_subRegion_id_fkey', 'country', type_='foreignkey')
    op.create_foreign_key(None, 'country', 'subRegion', ['subRegion_uuid'], ['uuid'])
    op.drop_column('country', 'subRegion_id')
    op.add_column('subRegion', sa.Column('region_uuid', sa.String(), nullable=True))
    op.drop_constraint(u'subRegion_region_id_fkey', 'subRegion', type_='foreignkey')
    op.create_foreign_key(None, 'subRegion', 'region', ['region_uuid'], ['uuid'])
    op.drop_column('subRegion', 'region_id')
    op.add_column('zone', sa.Column('country_uuid', sa.String(), nullable=True))
    op.drop_constraint(u'zone_country_id_fkey', 'zone', type_='foreignkey')
    op.create_foreign_key(None, 'zone', 'country', ['country_uuid'], ['uuid'])
    op.drop_column('zone', 'country_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zone', sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'zone', type_='foreignkey')
    op.create_foreign_key(u'zone_country_id_fkey', 'zone', 'country', ['country_id'], ['id'])
    op.drop_column('zone', 'country_uuid')
    op.add_column('subRegion', sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subRegion', type_='foreignkey')
    op.create_foreign_key(u'subRegion_region_id_fkey', 'subRegion', 'region', ['region_id'], ['id'])
    op.drop_column('subRegion', 'region_uuid')
    op.add_column('country', sa.Column('subRegion_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'country', type_='foreignkey')
    op.create_foreign_key(u'country_subRegion_id_fkey', 'country', 'subRegion', ['subRegion_id'], ['id'])
    op.drop_column('country', 'subRegion_uuid')
    # ### end Alembic commands ###
