"""empty message

Revision ID: 3499d4dae98a
Revises: c68a16387989
Create Date: 2017-03-28 14:11:52.675000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3499d4dae98a'
down_revision = 'c68a16387989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk', sa.Column('owner', sa.String(), nullable=False))
    op.create_foreign_key(None, 'risk', 'user', ['owner'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'risk', type_='foreignkey')
    op.drop_column('risk', 'owner')
    # ### end Alembic commands ###
