"""empty message

Revision ID: 433337456820
Revises: df4144ce98e9
Create Date: 2017-03-28 13:50:21.352000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433337456820'
down_revision = 'df4144ce98e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('tenant_uuid', sa.String(), nullable=False),
    sa.Column('createdBy', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sa.String(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('riskType_uuid', sa.String(), nullable=False),
    sa.Column('riskArea_uuid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['riskArea_uuid'], ['riskArea.uuid'], ),
    sa.ForeignKeyConstraint(['riskType_uuid'], ['riskType.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'tenant_uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk')
    # ### end Alembic commands ###
