"""empty message

Revision ID: 4478ab15f7b1
Revises: b27ac0083212
Create Date: 2017-03-23 13:33:55.827934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4478ab15f7b1'
down_revision = 'b27ac0083212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('causingFactor', sa.Column('causingFactorType_uuid', sa.String(), nullable=True))
    op.drop_constraint(u'causingFactor_causingFactorType_id_fkey', 'causingFactor', type_='foreignkey')
    op.create_foreign_key(None, 'causingFactor', 'causingFactorType', ['causingFactorType_uuid'], ['uuid'])
    op.drop_column('causingFactor', 'causingFactorType_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('causingFactor', sa.Column('causingFactorType_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'causingFactor', type_='foreignkey')
    op.create_foreign_key(u'causingFactor_causingFactorType_id_fkey', 'causingFactor', 'causingFactorType', ['causingFactorType_id'], ['id'])
    op.drop_column('causingFactor', 'causingFactorType_uuid')
    # ### end Alembic commands ###
