"""empty message

Revision ID: 458967b8340d
Revises: 538606942902
Create Date: 2017-03-20 09:40:12.441842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458967b8340d'
down_revision = '538606942902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('locked', sa.String(), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(), nullable=False))
    op.drop_column('user', 'groups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('groups', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'phone')
    op.drop_column('user', 'locked')
    # ### end Alembic commands ###
