"""empty message

Revision ID: 531736d68382
Revises: a28d7389b947
Create Date: 2017-03-24 07:40:38.216000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '531736d68382'
down_revision = 'a28d7389b947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('tenant_uuid', sa.String(), nullable=False),
    sa.Column('createdBy', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sa.String(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'tenant_uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('probability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('tenant_uuid', sa.String(), nullable=False),
    sa.Column('createdBy', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sa.String(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'tenant_uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('severity')
    op.drop_table('likelihood')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likelihood',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tenant_uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('createdBy', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modifiedBy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'likelihood_pkey'),
    sa.UniqueConstraint('title', 'tenant_uuid', name=u'likelihood_title_tenant_uuid_key'),
    sa.UniqueConstraint('uuid', name=u'likelihood_uuid_key')
    )
    op.create_table('severity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tenant_uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('createdBy', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modifiedBy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'severity_pkey'),
    sa.UniqueConstraint('title', 'tenant_uuid', name=u'severity_title_tenant_uuid_key'),
    sa.UniqueConstraint('uuid', name=u'severity_uuid_key')
    )
    op.drop_table('probability')
    op.drop_table('impact')
    # ### end Alembic commands ###
