"""empty message

Revision ID: 538a7b520587
Revises: 4478ab15f7b1
Create Date: 2017-03-23 13:36:05.087648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538a7b520587'
down_revision = '4478ab15f7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('causingFactor', sa.Column('causingFactorType_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'causingFactor_causingFactorType_uuid_fkey', 'causingFactor', type_='foreignkey')
    op.create_foreign_key(None, 'causingFactor', 'causingFactorType', ['causingFactorType_id'], ['id'])
    op.drop_column('causingFactor', 'causingFactorType_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('causingFactor', sa.Column('causingFactorType_uuid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'causingFactor', type_='foreignkey')
    op.create_foreign_key(u'causingFactor_causingFactorType_uuid_fkey', 'causingFactor', 'causingFactorType', ['causingFactorType_uuid'], ['uuid'])
    op.drop_column('causingFactor', 'causingFactorType_id')
    # ### end Alembic commands ###
