"""empty message

Revision ID: 59e3c94d66cf
Revises: 99339425dcee
Create Date: 2017-03-20 11:00:23.794784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e3c94d66cf'
down_revision = '99339425dcee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'causingFactor', ['uuid'])
    op.create_unique_constraint(None, 'country', ['uuid'])
    op.create_unique_constraint(None, 'eventType', ['uuid'])
    op.create_unique_constraint(None, 'likelihood', ['uuid'])
    op.create_unique_constraint(None, 'processArea', ['uuid'])
    op.create_unique_constraint(None, 'region', ['uuid'])
    op.create_unique_constraint(None, 'riskArea', ['uuid'])
    op.create_unique_constraint(None, 'riskResponse', ['uuid'])
    op.create_unique_constraint(None, 'riskType', ['uuid'])
    op.create_unique_constraint(None, 'severity', ['uuid'])
    op.create_unique_constraint(None, 'status', ['uuid'])
    op.create_unique_constraint(None, 'subRegion', ['uuid'])
    op.create_unique_constraint(None, 'treatmentType', ['uuid'])
    op.create_unique_constraint(None, 'user', ['uuid'])
    op.create_unique_constraint(None, 'valueChainArea', ['uuid'])
    op.create_unique_constraint(None, 'zone', ['uuid'])
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('tenant_uuid', sa.String(), nullable=False),
    sa.Column('createdBy', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sa.String(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('userGroups',
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('group_uuid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_uuid'], ['group.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('group_uuid', 'user_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zone', type_='unique')
    op.drop_constraint(None, 'valueChainArea', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'treatmentType', type_='unique')
    op.drop_constraint(None, 'subRegion', type_='unique')
    op.drop_constraint(None, 'status', type_='unique')
    op.drop_constraint(None, 'severity', type_='unique')
    op.drop_constraint(None, 'riskType', type_='unique')
    op.drop_constraint(None, 'riskResponse', type_='unique')
    op.drop_constraint(None, 'riskArea', type_='unique')
    op.drop_constraint(None, 'region', type_='unique')
    op.drop_constraint(None, 'processArea', type_='unique')
    op.drop_constraint(None, 'likelihood', type_='unique')
    op.drop_constraint(None, 'eventType', type_='unique')
    op.drop_constraint(None, 'country', type_='unique')
    op.drop_constraint(None, 'causingFactor', type_='unique')
    op.drop_table('userGroups')
    op.drop_table('group')
    # ### end Alembic commands ###
