"""empty message

Revision ID: 858da280709e
Revises: 1cb5bbad9ece
Create Date: 2017-03-17 16:09:45.740452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858da280709e'
down_revision = '1cb5bbad9ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('region', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('region', sa.Column('createdBy', sa.String(), nullable=True))
    op.add_column('region', sa.Column('modified', sa.DateTime(), nullable=True))
    op.add_column('region', sa.Column('modifiedBy', sa.String(), nullable=True))
    op.add_column('subRegion', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('subRegion', sa.Column('createdBy', sa.String(), nullable=True))
    op.add_column('subRegion', sa.Column('modified', sa.DateTime(), nullable=True))
    op.add_column('subRegion', sa.Column('modifiedBy', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subRegion', 'modifiedBy')
    op.drop_column('subRegion', 'modified')
    op.drop_column('subRegion', 'createdBy')
    op.drop_column('subRegion', 'created')
    op.drop_column('region', 'modifiedBy')
    op.drop_column('region', 'modified')
    op.drop_column('region', 'createdBy')
    op.drop_column('region', 'created')
    # ### end Alembic commands ###
