"""empty message

Revision ID: 8b224981bc71
Revises: 858da280709e
Create Date: 2017-03-19 13:30:19.398979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b224981bc71'
down_revision = '858da280709e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('abbr', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('tenant_uuid', sa.String(), nullable=True),
    sa.Column('createdBy', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modifiedBy', sa.String(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('subRegion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subRegion_id'], [u'subRegion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbr', 'tenant_uuid'),
    sa.UniqueConstraint('title', 'tenant_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country')
    # ### end Alembic commands ###
