"""empty message

Revision ID: 99339425dcee
Revises: 99852cbb06bd
Create Date: 2017-03-20 10:55:08.856937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99339425dcee'
down_revision = '99852cbb06bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
