"""empty message

Revision ID: 99852cbb06bd
Revises: faac5ec77dbd
Create Date: 2017-03-20 10:31:49.039635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99852cbb06bd'
down_revision = 'faac5ec77dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    # ### end Alembic commands ###
