"""empty message

Revision ID: a0f41692b4c5
Revises: a2588aa3743d
Create Date: 2017-03-19 16:40:39.378926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0f41692b4c5'
down_revision = 'a2588aa3743d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('causingFactor', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('causingFactor', 'createdBy',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('causingFactor', 'tenant_uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('causingFactor', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('causingFactor', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('processArea', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('processArea', 'createdBy',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('processArea', 'tenant_uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('processArea', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('processArea', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('riskArea', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('riskArea', 'createdBy',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('riskArea', 'tenant_uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('riskArea', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('riskArea', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('riskType', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('riskType', 'createdBy',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('riskType', 'tenant_uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('riskType', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('riskType', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('valueChainArea', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('valueChainArea', 'createdBy',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('valueChainArea', 'tenant_uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('valueChainArea', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('valueChainArea', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('valueChainArea', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('valueChainArea', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('valueChainArea', 'tenant_uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('valueChainArea', 'createdBy',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('valueChainArea', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('riskType', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('riskType', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('riskType', 'tenant_uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('riskType', 'createdBy',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('riskType', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('riskArea', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('riskArea', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('riskArea', 'tenant_uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('riskArea', 'createdBy',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('riskArea', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('processArea', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('processArea', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('processArea', 'tenant_uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('processArea', 'createdBy',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('processArea', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('causingFactor', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('causingFactor', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('causingFactor', 'tenant_uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('causingFactor', 'createdBy',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('causingFactor', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
