"""empty message

Revision ID: a129952d9f05
Revises: a9a28384e63c
Create Date: 2017-03-22 11:38:30.237000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a129952d9f05'
down_revision = 'a9a28384e63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('tenant_uuid', sa.String(), nullable=False),
    sa.Column('createdBy', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sa.String(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('treatmentType_id', sa.Integer(), nullable=True),
    sa.Column('riskResponse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['riskResponse_id'], ['riskResponse.id'], ),
    sa.ForeignKeyConstraint(['treatmentType_id'], ['treatmentType.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'tenant_uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treatment')
    # ### end Alembic commands ###
