"""empty message

Revision ID: ac51d27bf5ff
Revises: 8d9de0542944
Create Date: 2017-03-22 09:07:11.360000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac51d27bf5ff'
down_revision = '8d9de0542944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'causingFactor_causingFactorType_id_fkey', 'causingFactor', type_='foreignkey')
    op.drop_column('causingFactor', 'causingFactorType_id')
    op.add_column('causingFactor', sa.Column('causingFactorType_uuid', sa.String(), nullable=True))
    op.create_foreign_key(None, 'causingFactor', 'causingFactorType', ['causingFactorType_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('causingFactor', sa.Column('causingFactorType_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'causingFactor', type_='foreignkey')
    op.create_foreign_key(u'causingFactor_causingFactorType_id_fkey', 'causingFactor', 'causingFactorType', ['causingFactorType_id'], ['id'])
    op.drop_column('causingFactor', 'causingFactorType_uuid')
    # ### end Alembic commands ###
