"""empty message

Revision ID: b27ac0083212
Revises: a129952d9f05
Create Date: 2017-03-23 13:16:20.073406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27ac0083212'
down_revision = 'a129952d9f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'causingFactor_causingFactorType_id_fkey', 'causingFactor', type_='foreignkey')
    op.create_foreign_key(None, 'causingFactor', 'causingFactorType', ['causingFactorType_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'causingFactor', type_='foreignkey')
    op.create_foreign_key(u'causingFactor_causingFactorType_id_fkey', 'causingFactor', 'causingFactorType', ['causingFactorType_id'], ['id'])
    # ### end Alembic commands ###
