"""empty message

Revision ID: b2c4124d3711
Revises: 3feef69b3fe6
Create Date: 2017-03-21 11:40:47.364000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c4124d3711'
down_revision = '3feef69b3fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('desc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'desc')
    # ### end Alembic commands ###
