"""empty message

Revision ID: b6f3f1bd38ef
Revises: a0f41692b4c5
Create Date: 2017-03-20 09:08:04.994572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f3f1bd38ef'
down_revision = 'a0f41692b4c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('initials', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('roles', sa.String(), nullable=False),
    sa.Column('groups', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('contact', sa.Boolean(), nullable=True),
    sa.Column('tenant_uuid', sa.String(), nullable=False),
    sa.Column('createdBy', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sa.String(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'tenant_uuid'),
    sa.UniqueConstraint('initials', 'tenant_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
