"""empty message

Revision ID: c1bb096dfc35
Revises: 531736d68382
Create Date: 2017-03-24 07:45:23.788000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1bb096dfc35'
down_revision = '531736d68382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('causingFactor', 'causingFactorType_uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('country', 'subRegion_uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subRegion', 'region_uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('treatment', 'riskResponse_uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('treatment', 'treatmentType_uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('valueChain', 'valueChainArea_uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('zone', 'country_uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zone', 'country_uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('valueChain', 'valueChainArea_uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('treatment', 'treatmentType_uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('treatment', 'riskResponse_uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subRegion', 'region_uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('country', 'subRegion_uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('causingFactor', 'causingFactorType_uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
