"""empty message

Revision ID: d8897ccab3f6
Revises: 0bd327c377bc
Create Date: 2017-03-19 16:28:22.453180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8897ccab3f6'
down_revision = '0bd327c377bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country', 'abbr',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('country', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('country', 'createdBy',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('country', 'tenant_uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('country', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('country', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subRegion', 'abbr',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('subRegion', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('subRegion', 'createdBy',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subRegion', 'tenant_uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subRegion', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('subRegion', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('zone', 'abbr',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('zone', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('zone', 'createdBy',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('zone', 'tenant_uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('zone', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('zone', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zone', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('zone', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('zone', 'tenant_uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('zone', 'createdBy',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('zone', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('zone', 'abbr',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('subRegion', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subRegion', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('subRegion', 'tenant_uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subRegion', 'createdBy',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subRegion', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('subRegion', 'abbr',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('country', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('country', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('country', 'tenant_uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('country', 'createdBy',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('country', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('country', 'abbr',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
