"""empty message

Revision ID: e188acc28f52
Revises: eff9bca76c3d
Create Date: 2017-03-24 08:18:17.314000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e188acc28f52'
down_revision = 'eff9bca76c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'table',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('log', 'tableRow_uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'tableRow_uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('log', 'table',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
