"""empty message

Revision ID: e671a37c6ec1
Revises: e188acc28f52
Create Date: 2017-03-24 13:46:55.171000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e671a37c6ec1'
down_revision = 'e188acc28f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('tenant_uuid', sa.String(), nullable=False),
    sa.Column('createdBy', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modifiedBy', sa.String(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('impact_uuid', sa.String(), nullable=False),
    sa.Column('probability_uuid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['impact_uuid'], ['impact.uuid'], ),
    sa.ForeignKeyConstraint(['probability_uuid'], ['probability.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('impact_uuid', 'probability_uuid', 'tenant_uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    # ### end Alembic commands ###
