"""empty message

Revision ID: eed135efce5b
Revises: e671a37c6ec1
Create Date: 2017-03-27 12:13:08.997000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed135efce5b'
down_revision = 'e671a37c6ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('impact', sa.Column('cost', sa.String(), nullable=True))
    op.add_column('impact', sa.Column('legal', sa.String(), nullable=True))
    op.add_column('impact', sa.Column('other', sa.String(), nullable=True))
    op.add_column('impact', sa.Column('requirements', sa.String(), nullable=True))
    op.add_column('impact', sa.Column('schedule', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('impact', 'schedule')
    op.drop_column('impact', 'requirements')
    op.drop_column('impact', 'other')
    op.drop_column('impact', 'legal')
    op.drop_column('impact', 'cost')
    # ### end Alembic commands ###
