"""empty message

Revision ID: eff9bca76c3d
Revises: c1bb096dfc35
Create Date: 2017-03-24 08:07:21.166000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff9bca76c3d'
down_revision = 'c1bb096dfc35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('tenant_uuid', sa.String(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('table', sa.String(), nullable=False),
    sa.Column('tableRow_uuid', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    # ### end Alembic commands ###
